puppetlabs/puppetlabs-chocolatey

.sync.yml
.travis.yml
CONTRIBUTING.md
Gemfile
License
MAINTAINERS.md
NOTICE

The PR contains the updates from the new modsync config for windows;
- LICENSE, NOTICE, CONTRIBUTING, MAINTAINERS updates (where applicable)
- Gemfile, Appveyor, Travis, gitignore cleanup
https://github.com/puppetlabs/modulesync_configs/pull/66
https://github.com/puppetlabs/modulesync_configs/pull/63
https://github.com/puppetlabs/modulesync_configs/pull/62
https://github.com/puppetlabs/modulesync_configs/pull/61

(maint) modsync update - master

---

CONTRIBUTING.md
README.md
metadata.json
templates/InstallChocolatey.ps1.erb

Update all references from puppetlabs to puppet

(MODULES-3356) Branding Name Change

---

CHANGELOG.md
README.md
metadata.json

Update the Changelog, ReadMe, and metadata.json for release.

(FM-4966) Release unsupported 0.7.0

---

.gitignore
Gemfile
Rakefile

Module updated with lastest modsync settings

(MODULES-3536) modsync update

---

README.md

Needs development edit from @jbondpdx, then in-depth technical review from windows team member. Please do not merge until these steps have been completed.

(docs) Update README to current module readme style guidelines.

---

.sync.yml
Gemfile

https://github.com/puppetlabs/modulesync_configs/pull/104

Workaround frozen strings on ruby 1.9

---

CHANGELOG.md

(maint) bump release date

---

.gitignore
.rspec
.sync.yml
.travis.yml
Gemfile
spec/classes/config_spec.rb
spec/classes/init_spec.rb
spec/classes/install_spec.rb
spec/spec.opts

Includes cleanup of .sync.yml to remove stuff already present in config defaults.

(FM-5972) Update to next modulesync_configs [dedaf10]

---

CHANGELOG.md
metadata.json

This commit prepares the module for the 2.0.2 release for the 4th April

(MODULES-4633) Prepare for 2.0.2 module release

---

metadata.json

Metadata update for new version requirement and issues_url #puppethack

(MODULES-4846) Update metadata 

---

CHANGELOG.md
metadata.json

This commit prepares the module for 3.0.0 release.

(MODULES-4994) Prepare module for 3.0.0 release

---

lib/facter/chocolateyversion.rb

Added a choco_ver variable and then string it (to_s) it to avoid the rendering error.

add choco_ver variable and string it

---

CHANGELOG.md
metadata.json

This commit prepares the module for a v3.1.0 release.

(MODULES-8053) Prepare for 3.1.0 release

---

README.md

This commit makes minor edits.

(MODULES-8634) Minor README edit

---

CHANGELOG.md

Add community contributions. Fix a ticket number.

(MAINT) Add to changelog

---

README.md

This commit makes minor edits to the README.

(MODULES-8739) DOCS Release Review

---

spec/unit/facter/choco_install_path_spec.rb
spec/unit/facter/choco_temp_dir.rb
spec/unit/facter/chocolateyversion_spec.rb
spec/unit/puppet_x/chocolatey/chocolatey_common_spec.rb
spec/unit/puppet_x/chocolatey/chocolatey_install_spec.rb
spec/unit/puppet_x/chocolatey/chocolatey_version_spec.rb

to facilitate more complete test output from our unit tests.

(WIN-280) add skip() unless pattern to tests

---

metadata.json

(MODULES-9614) dependencychecker - update stdlib version

---

.sync.yml
metadata.json

(maint) update .sync.yaml file and pdk update

---

CHANGELOG.md
REFERENCE.md
metadata.json

(MODULES-10003) Release Prep v5.0.0

---

.github/workflows/release.yml

Add Github Actions release workflow

---

.github/workflows/release.yml
.sync.yml
.travis.yml
Rakefile
appveyor.yml
metadata.json
spec/spec_helper.rb

"(IAC-365) updating tokens and dataset for honeycomb"
pdk version: `1.16.0`

(IAC-365) updating tokens and dataset for honeycomb

---

.github/workflows/nightly.yml
.github/workflows/pr_test.yml
.rubocop.yml
Rakefile
lib/puppet_x/chocolatey/chocolatey_common.rb
metadata.json

Update gha templates
pdk version: `1.19.0.pre (47)`

pdksync - Update gha templates

---

README.md
lib/puppet/provider/package/chocolatey.rb
spec/unit/puppet/provider/package/chocolatey_spec.rb

This pul request add support for version ranges as ensure value.

add support for version range

---

CHANGELOG.md
metadata.json

Release job failed so did a manual one

(maint) Release prep v6.1.0

---

lib/puppet/provider/package/chocolatey.rb
spec/unit/puppet/provider/package/chocolatey_spec.rb

The package provider did not support holdable anymore since there were various changes in the type. The ensure parameter does not support the :mark value anymore. Instead, if a package should be held, it has to be done with the :mark property. This change updates the provider to support the :mark property and therefore support holdable again.
- support ensure => mark for puppet 6 with the implementation of the 'deprecated_hold' function
- add support for property mark
- add rspec tests

update holdable feature

---

README.md

- Updating README.md with Deferred function example for sensitive fields.

(CONT-596) - Updating readme with deferred function for sensitive fields

---

README.md
manifests/install.pp
templates/InstallChocolatey.ps1.epp

Converting erb template to epp template.
Add any additional context about the problem here. 
Mention any related issues or pull requests.

[CAT-1142] : Converting erb template to epp template
