- appveyor.yml
Running gem install bundler on appveyor is redundant because it is already present.
Removing it will speed up build times
> (FM-4881) Remove gem install bundler on Appveyor

- Rakefile
This commit adds the usual rake tasks from the ACL
module into the chocolatey module.  The test rake
test is required by Puppetlabs build pipelines.
> (MODULES-3161) Add rake tests task

- README.md
This commit updates the README.md and references Puppet Labs
- Change the build badges to the Puppetlabs Travis and Appveyor
projects
- Remove references to issues on original fork
- Removed reference to the issues list as that should be in
Puppetlabs JIRA instance
- Changed the development text to be inline with other Puppetlabs
modules
- Added Rob Reynolds to the attributions as the original code was
forked from his repository
> (maint) Update readme with puppetlabs references

- metadata.json
This commit modifies the module metadata to reflect the module's
minimum specifications;
- Windows Server 2003 is not supported
- Puppet below 3.0 is not supported
This commit also changes the module namespace to puppetlabs and
changes the version back to 0.0.1 as this is the first time this
module has been authored.
> (MODULES-3209) Modify metadata with minimum specifications

- acceptance/.beaker-git.cfg
- acceptance/.beaker-pe.cfg
- acceptance/config/windows-2008r2-x86_64.cfg
- acceptance/config/windows-2012r2-core-x86_64.cfg
- acceptance/config/windows-2012r2-x86_64.cfg
- acceptance/scripts/beaker_command_w2008r2x64.sh
- acceptance/scripts/beaker_command_w2012r2x64.sh
- acceptance/setup/install.rb
- acceptance/tests/chocolatey_spec.rb
This commit adds the files necessary for the acceptance beaker tests
for CI.  An initial blank test file is included which will always pass.
It is expected that the test suite will be filled out in later commits.
These files originally came from the puppetlabs-acl module.
> (MODULES-3161) Add acceptance test harness

- tests/acceptance/pre-suite/00_pe_install.rb
- tests/acceptance/pre-suite/02_chocolatey_application_install.rb
- tests/lib/chocolatey_helper.rb
- tests/reference/pre-suite/03_chocolatey_application_install.rb
Added reference and acceptance tests for installing the Chocolatey application via the Chocolatey Module.
https://tickets.puppetlabs.com/browse/MODULES-3043
> (MODULES-3043) add acceptance and reference test for choco install

- tests/configs/windows-2008r2-64a
- tests/configs/windows-2008r2-64mda
WMF5 templates need updating, this will allow us to make the pipeline green, and test older versions of powershell before we update the vm templates with the latest version of wmf5.
> Change templates to use windows 2008r2 without wmf5

- .gitignore
- .sync.yml
- examples/init.pp
- lib/facter/chocolateyversion.rb
- lib/puppet/provider/chocolateysource/windows.rb
- lib/puppet/provider/package/chocolatey.rb
- lib/puppet/type/chocolateysource.rb
- lib/puppet_x/chocolatey/chocolatey_common.rb
- lib/puppet_x/chocolatey/chocolatey_install.rb
- lib/puppet_x/chocolatey/chocolatey_version.rb
- manifests/config.pp
- spec/spec_helper.rb
- spec/unit/facter/choco_install_path_spec.rb
- spec/unit/facter/chocolateyversion_spec.rb
- spec/unit/puppet/provider/chocolateysource/windows_spec.rb
- spec/unit/puppet/provider/package/chocolatey_spec.rb
- spec/unit/puppet/type/chocolateysource_spec.rb
- spec/unit/puppet_x/chocolatey/chocolatey_common_spec.rb
- spec/unit/puppet_x/chocolatey/chocolatey_install_spec.rb
- spec/unit/puppet_x/chocolatey/chocolatey_version_spec.rb
Provide the ability manage a source with a custom type and provider.
This allows a source to be ensurable, and also allows for a source to
be manageable in the same converge that Chocolatey is installed
during. This further allows for installing packages from custom
sources all in the same Puppet run.
> (MODULES-3037) Manage sources

- lib/facter/choco_install_path.rb
- spec/unit/facter/choco_install_path_spec.rb
Confine the choco_install_path to Windows osfamily (taking the the
example from other modules that do similar confines) and ensure that
the default is passed back if ChocolateyInstall.install_path comes back
nil.
> (MODULES-3037) Confine install path fact w/default

- lib/facter/chocolateyversion.rb
- spec/unit/facter/choco_install_path_spec.rb
- spec/unit/facter/chocolateyversion_spec.rb
Confine the chocolateyversion fact to Windows osfamily and ensure that
the default of 0 is passed back if ChocolateyVersion.version comes back
nil.
> (MODULES-3037) Confine version fact w/default

- tests/reference/tests/chocolateysource/apply_manifest_without_location.rb
- tests/reference/tests/chocolateysource/fail_to_appy_bad_manifest.rb
- tests/reference/tests/chocolateysource/fail_to_set_password_without_user.rb
- tests/reference/tests/chocolateysource/fail_to_set_user_without_password.rb
- tests/reference/tests/chocolateysource/remove_user_pass_from_existing_source.rb
Adds negative tests for:
* applying a bad manifest
* trying to set a password with no user name
* trying to set a uersname with no password
Adds test for overwriting the source location. The default chocolatey behavior of overwriting source with the name
of a resource should be discussed.
> (MODULES-3037) Acceptance tests - ChocolateySource

- README.md
- lib/puppet/provider/chocolateyfeature/windows.rb
- lib/puppet/type/chocolateyfeature.rb
- lib/puppet/type/chocolateysource.rb
- spec/unit/puppet/provider/chocolateyfeature/windows_spec.rb
- spec/unit/puppet/type/chocolateyfeature_spec.rb
- tests/reference/tests/chocolateyfeature/disable_disabled_feature.rb
- tests/reference/tests/chocolateyfeature/disable_enabled_feature.rb
- tests/reference/tests/chocolateyfeature/enable_disabled_feature.rb
- tests/reference/tests/chocolateyfeature/enable_enabled_feature.rb
- tests/reference/tests/chocolateyfeature/fail_to_enable_nonexistent_feature.rb
- tests/reference/tests/chocolateyfeature/fail_to_remove_feature.rb
Supersedes #23. 
Support enabling or disabling chocolatey features.
Add documentation and reference tests.
> (MODULES-3034) Feature Configuration

- README.md
- lib/puppet/provider/chocolateyconfig/windows.rb
- lib/puppet/type/chocolateyconfig.rb
- spec/unit/puppet/provider/chocolateyconfig/windows_spec.rb
- spec/unit/puppet/type/chocolateyconfig_spec.rb
- tests/lib/chocolatey_helper.rb
- tests/reference/tests/chocolateyconfig/add_new_config_item.rb
- tests/reference/tests/chocolateyconfig/add_value_to_existing_config.rb
- tests/reference/tests/chocolateyconfig/change_config_value.rb
- tests/reference/tests/chocolateyconfig/ensure_config_value_with_password_in_name.rb
- tests/reference/tests/chocolateyconfig/fail_to_appy_bad_manifest.rb
- tests/reference/tests/chocolateyconfig/fail_to_set_present_without_value.rb
- tests/reference/tests/chocolateyconfig/remove_config_value_with_password_in_name.rb
- tests/reference/tests/chocolateyconfig/remove_value_from_config.rb
~~Requires #1 to be merged first.~~
Provide the ability to manage config settings with a custom type and
provider. This allows a config setting to be ensurable, and also
allows for a config settings to be manageable in the same converge
that Chocolatey is installed during.
Things to accomplish:
> (MODULES-3035) Manage configuration settings

- .sync.yml
- Gemfile
- tests/configs/windows-2012r2-64a
- tests/configs/windows-2012r2-64mda
- tests/reference/tests/chocolateypackage/install_and_remove_good_package.rb
- tests/reference/tests/chocolateypackage/install_and_remove_good_package_utf-8.rb
- tests/reference/tests/hello.rb
Tests for installing and removing packages with and without UTF-8 characters.
Currently failing to apply the manifest correctly for package with UTF-8 characters, see  install_and_remove_good_package_utf-8.rb line 60.
> (MODULES-3275) Chocolatey module testing

- tests/reference/tests/chocolateypackage/install_and_remove_good_package.rb
- tests/reference/tests/chocolateypackage/install_and_remove_good_package_utf-8.rb
Added "retry_on" to vlc uninstall command.
Removed check for vlc.exe actually being removed thus placing a high amount of faith in the proper execution of the "retry_on" command. This is risk that we're taking, but it has a low probability of interfering with other tests so long as we don't reuse the vlc package in other tests.
> (MODULES-3275) fix VLC uninstall command

- Rakefile
- spec/spec_helper.rb
The bundle exec rake test command in the chocolatey Rakefile runs an incomplete set of tests with a missing dependency on `bundle exec rake spec_prep`. After further investigation, it turns out `puppetlabs_spec_helper` defines `rake spec` which runs all the spec tests and does appropriate prep setup/teardown. After discussing with @glennsarti and @ThoughtCrhyme it seems like the correct call here is to run `bundle exec rake spec` instead of extending `bundle exec rake test` to further duplicate it.
This PR specifically just removes the `rake test` task from Rakefile to avoid further confusion. It is believed that since the module is pre-1.0 this change, which might be considered backwards-incompatible is acceptable. I'm happy to work up something more backwards-compatible via task …
> (Modules 3391) remove `rake test` and fix failing test

- .fixtures.yml
- README.md
- manifests/install.pp
- metadata.json
- spec/classes/install_spec.rb
It was originally required to set the environment variables prior
to running Chocolatey install to help prepare the environment for
suitability. It was originally added in 5a849adca and ad57d1429
to ensure that Chocolatey could be suitable to be installed and
used to install packages on the first run. This was also to
ensure that you could override the Chocolatey install directory
by setting the value in advance of the install.
In b5034d167 @rismoney removed the necessity for pre-setting the
environment variable as it was passed to the install exec.
We have since determined that the providers default to a location
of `$env:ALLUSERSPROFILE\chocolatey\bin\choco.exe` when an install
path cannot be found. https://github.com/puppetlabs/puppetlabs-chocolatey/blob/fa67417bbfac06049f36346e02eb09dd …
> (MODULES-3641) Remove Windows_env module dependency

- lib/puppet_x/chocolatey/chocolatey_common.rb
When Chocolatey has been installed and not yet run, the config file
doesn't exist. So chocolateyconfig, chocolateyfeature, and
chocolateysource will all fail until the config file exists.
Trigger a version check before returning the config file in
`PuppetX::Chocolatey::ChocolateyCommon.choco_config_file`. This
will ensure that an installed Chocolatey will have had the chance
to run at least one time if it is installed, thus ensuring the
config file's existence, allowing the providers to work without
erroring on a missing config file.
> (MODULES-3677) Ensure Chocolatey Config

- README.md
- lib/puppet/provider/chocolateyconfig/windows.rb
- lib/puppet/provider/chocolateyfeature/windows.rb
- lib/puppet/provider/chocolateysource/windows.rb
- lib/puppet/type/chocolateysource.rb
- spec/unit/puppet/provider/chocolateysource/windows_spec.rb
- spec/unit/puppet/type/chocolateysource_spec.rb
- tests/reference/tests/chocolateysource/disable_existing_source_two_runs.rb
During the check for insync, user keeps getting detected for synchronize
due to the default value being set to '' as compared to a nil value
being returned from the existing items.
This can cause errors as it could set a source to enabled, even if the
source should be disabled. Instead we should set a default for the
existing item so it matches the default in the user property.
Still needs:
Fixes for MODULES-3430 have also been included.
> (MODULES-3758) Fix: chocolateysource user ensure sync

- lib/puppet/provider/package/chocolatey.rb
- lib/puppet_x/chocolatey/chocolatey_common.rb
- spec/unit/puppet/provider/package/chocolatey_spec.rb
This might need a ticket @jpogran / @puppetlabs/windows 
A few maintenance fixes that I've been wanting to do prior to the release, the bigger of which is to add the ignore package exit codes.
> (MODULES-3880) Ignore Package Exit Codes

- README.md
C:\Chocolatey is not a desired installation location by default.
Provide helpful information on this and what someone can do if they
absolutely must install to that location.
Also provide information on security settings that alternative
locations will need. Chocolatey only locks down the default
installation directory.
> (MODULES-4090) Document installation considerations

- templates/InstallChocolatey.ps1.erb
When ensuring Chocolatey's installation, attempt to set 
TLS 1.1 / TLS 1.2 when it is available and provide a message 
when it is not available. This will be helpful when attempting
to determine when an error is occurring with older 
PowerShells and .NETs in environments that have restrictions
set on TLS.
> (maint) Set TLS 1.1+ When Available (For Ensure Chocolatey Installation)

- lib/puppet_x/chocolatey/chocolatey_version.rb
- spec/unit/puppet_x/chocolatey/chocolatey_version_spec.rb
When determining the version of Chocolatey that is installed, the
module calls `choco -v` which will return the version in most versions
of Chocolatey (anything earlier than 0.9.8.24 or more than 4 years old
may not). However sometimes there is messaging that tends to be
presented as warnings that still end up being included in the output.
Instead of looking for specific wording, typically the chocolatey
version is going to be the last line in the output. So remove all of
the other lines and just use the last line available.
Using a simpler `string.lines.last` is out because it only splits
on `$/` and doesn't allow multiple options. So split on CRLF, then LF,
then CR. This allows the output to be evaluated on different
platforms and not be subject to whatever Ruby believes `$/` evaluates …
> (MODULES-4135) choco -v - Remove all extraneous messaging

- .fixtures.yml
- manifests/config.pp
- manifests/install.pp
- metadata.json
Previously, ensuring the installation directory for Chocolatey
keyed off of an environment value passed to an exec powershell
resource through the environment parameter. However there is a
bug in the powershell module in versions 2.x up to 2.1.0
(current version as of this commit) that ignore the environment
parameter. Since it is better to explicitly set that value, take
a dependency on the registry module and explicitly ensure the
environment variable is set so that Chocolatey will successfully
install to an alternative install location.
> (MODULES-4091) Explicitly Set ChocolateyInstall Environment

- lib/puppet/provider/chocolateyconfig/windows.rb
- lib/puppet/provider/chocolateyfeature/windows.rb
- lib/puppet/provider/chocolateysource/windows.rb
- spec/unit/puppet/provider/chocolateyconfig/windows_spec.rb
- spec/unit/puppet/provider/chocolateyfeature/windows_spec.rb
- spec/unit/puppet/provider/chocolateysource/windows_spec.rb
When attempting to force the provider, validation would error due
to the version coming back would not be above the version that is
being validated. When the provider is unsuitable, it should not
return an error during the Puppet run and should instead just
return the unsuitable message.
Check to ensure Chocolatey is installed prior to allowing the
validation check to not fail the Puppet run.
> (MODULES-4149) Unsuitable providers should not error

- lib/puppet/provider/package/chocolatey.rb
- spec/unit/puppet/provider/package/chocolatey_spec.rb
Previously, when there were no sources enabled, Puppet would
attempt to loop over a non-existent set of packages pulled back
from listing a set of packages locally. Unfortunately this is due
to an issue in Chocolatey that requires at least one source to be
enabled to produce the local set of installed packages:
https://github.com/chocolatey/choco/issues/661
Instead of allowing Puppet to fail on a nil:NilClass error, provide
a helpful and actionable message instead.
> (MODULES-4056) Helpful Error if No Sources Enabled

- templates/InstallChocolatey.ps1.erb
At least in Windows 10, the use of COM objects for unizp does not seem
to work in a non-interactive session
> (MODULES-4210) Do not use com unzip in PS 5+

- spec/classes/coverage_spec.rb
Previously, the specs were run in serial, or in larger chunks in parallel.
Unfortunately this hides errors where spec files don't explicitly load all
requires before loading.  This commit adds the require spec_helper to any
remaining spec files so that parallel spec can complete correctly.
> (maint) Fix parallel spec issue with coverage_spec

- lib/puppet/provider/package/chocolatey.rb
- spec/unit/puppet/provider/package/chocolatey_spec.rb
Using one dash instead of two for a parameter causes chocolatey to think
the parameter is a bundled option (like -dvyf means --debug --verbose
--confirm --force).
> (Modules-4508) Fixed error with version parameter

- .sync.yml
- Gemfile
- Rakefile
Re-added the rototiller gem to .sync and Gemfile; set minimum version to 1.0.
Added a fail condition if a rototiller command is called without the gem present so we don't see this happen silently again.
Moved rototiller gem to Development group.
> (MODULES-4601) Fail rototiller task correctly.

- lib/puppet/provider/chocolateyconfig/windows.rb
- lib/puppet/provider/chocolateyfeature/windows.rb
- lib/puppet/provider/chocolateysource/windows.rb
- spec/unit/puppet/provider/chocolateyconfig/windows_spec.rb
- spec/unit/puppet/provider/chocolateyfeature/windows_spec.rb
- spec/unit/puppet/provider/chocolateysource/windows_spec.rb
Previously, any providers managing Chocolatey configuration are unable
to be used with 0.10.4+ and actually cause the process to
fail.
Chocolatey 0.10.4+ has changed the way it updates and accesses the
config. The new method has exposed an error in an unclosed file handle
when reading the configuration for `chocolateysource`,
`chocolateyfeature`, and `chocolateyconfig`. Switch to `File.read` as
it will automatically close the file after reading out the contents.
> (MODULES-4678) Explicitly close config on read

- .sync.yml
- Gemfile
- appveyor.yml
- spec/unit/puppet/provider/package/chocolatey_spec.rb
This commit pins rspec-puppet to '< 2.6.0' due to a bug in rspec-puppet
(rodjek/rspec-puppet#577)
> (MODULES-5187)(MODULES-5356) Pin rspec-puppet to 2.5.x

- Rakefile
- spec/acceptance/config_values_spec.rb
- spec/acceptance/features_spec.rb
- spec/acceptance/package_spec.rb
- spec/acceptance/sources_spec.rb
- spec/spec_helper.rb
- spec/spec_helper_acceptance.rb
- spec/support/examples/failing_manifest.rb
- spec/support/examples/manifest_removes_value.rb
- spec/support/examples/password_value_should_be.rb
- spec/support/examples/successful_config_change.rb
- spec/support/utilities/helpers.rb
This change converts the module tests to the more standardized RSpec tests.
> (MODULES-6746) Convert Tests to RSpec

- Gemfile
- spec/acceptance/features_spec.rb
- spec/acceptance/package_spec.rb
- spec/acceptance/sources_spec.rb
- spec/spec_helper_acceptance.rb
- spec/support/examples/failing_manifest.rb
- spec/support/examples/manifest_removes_value.rb
- spec/support/examples/password_value_should_be.rb
- spec/support/examples/successful_config_change.rb
- spec/support/utilities/helpers.rb
This change adds beaker/testmode_switcher to the module, ensuring that
tests are run properly whether the current host set up is agent only, or
has a master.
> (MODULES-6734) Add Beakser Testmode Switcher

- spec/acceptance/package_spec.rb
- spec/support/utilities/helpers.rb
Prior to this commit the URIs for chocolatey feeds in the acceptance test
suite pointed to the old nexus feeds which have gone dark. This caused the
acceptance tests to fail.  This commit updates those URLs to point to the
new and functional artifactory feeds instead, fixing the acceptance tests.
> (MAINT) Update chocolatey sources to artifactory

- spec/support/utilities/helpers.rb
Due to puppet packaging curl at C:/ProgramFiles64Folder/PuppetLabs/Puppet/puppet/ssl/cert.pem we have added a "cacert" parameter to chocolatey's "curl_on" command to point at the correct cert-bundle at C:\Program Files\Puppet Labs\Puppet\puppet\ssl\cert.pem.
This change may be reverted in the future if we remove puppets packaged curl or otherwise change its cert file path to the correct path.
> (WIN-231) Change curl_on command to add path to cacert bundle

- lib/puppet_x/chocolatey/chocolatey_version.rb
This fixes an issue where warning is thrown that a OLD_CHOCO_MESSAGE constant is already initialized when a "puppet apply" is used (does not occur within a "puppet agent" run). The warning this fixes is as per the output below:
```
[root@master ~]# puppet apply -e 'notice("test")'
/opt/puppetlabs/puppet/cache/lib/puppet_x/chocolatey/chocolatey_version.rb:8: warning: already initialized constant PuppetX::Chocolatey::ChocolateyVersion::OLD_CHOCO_MESSAGE
/etc/puppetlabs/code/environments/production/modules/chocolatey/lib/puppet_x/chocolatey/chocolatey_version.rb:8: warning: previous definition of OLD_CHOCO_MESSAGE was here
Notice: Scope(Class[main]): test
Notice: Compiled catalog for master.paulreed.ca in environment production in 0.15 seconds
Notice: Applied catalog in 0.92 seconds
```
> (MODULES-5859) Fix An already initialized constant' warning when doing a "puppet apply"

- README.md
- manifests/init.pp
- manifests/install.pp
- spec/classes/init_spec.rb
- templates/InstallChocolatey.ps1.erb
Add a new parameter `install_proxy` to specify a proxy server to use during installation in the form `http://proxy.megacorp.com:3128`.  This will be conditionally munged into the `InstallChocolatey.ps1.erb` script and used to configure the `System.Net.WebRequest` instance which is used to download all required assets
> (MODULES-5654) Support for proxies during installation

- lib/puppet_x/chocolatey/chocolatey_common.rb
This commit adds unless defined statements around the constant initialization to avoid warnings
> MODULES-7068 Only initialise constant when not defined

- CHANGELOG.md
- README.md
- lib/puppet/provider/chocolateysource/windows.rb
- lib/puppet/type/chocolateysource.rb
- spec/acceptance/sources_spec.rb
- spec/unit/puppet/provider/chocolateysource/windows_spec.rb
- spec/unit/puppet/type/chocolateysource_spec.rb
Prior to this commit the `chocolateysource` type and provider did
not support the option to specify the `--bypass-proxy` flag when
managing a source. This option causes Chocolatey to ignore any
system proxies and was introduced in Chocolatey `0.10.4`.
This commit adds the `bypass_proxy` property to the type and
provider of `chocolateysource` to ensure that this property
can be configured on versions which support it.
This commit also updates the README documentation and CHANGELOG,
as well as providing new unit and acceptance tests and updating
any unit and acceptance tests which should include the new
setting.
As new features are added which depend on particular versions of
Chocolatey, it may be useful to refactor the tests and provider
to manage the addition of such features with less …
> (MODULES-4418) Add bypass_proxy to chocolateysource

- CHANGELOG.md
- README.md
- lib/puppet/provider/chocolateysource/windows.rb
- lib/puppet/type/chocolateysource.rb
- spec/acceptance/sources_spec.rb
- spec/unit/puppet/provider/chocolateysource/windows_spec.rb
- spec/unit/puppet/type/chocolateysource_spec.rb
Prior to this commit the `chocolateysource` type and provider did
not support the option to specify the `--admin-only` flag when
managing a source. This option causes Chocolatey to markthe source
as visible only to admins  and was introduced in Chocolatey `0.10.8`.
This commit adds the `admin_only` property to the type and
provider of `chocolateysource` to ensure that this property
can be configured on versions which support it.
This commit also updates the README documentation and CHANGELOG,
as well as providing new unit and acceptance tests and updating
any unit and acceptance tests which should include the new
setting.
> (MODULES-5898) add admin_only to chocolateysource

- CHANGELOG.md
- README.md
- lib/puppet/provider/chocolateysource/windows.rb
- lib/puppet/type/chocolateysource.rb
- spec/acceptance/sources_spec.rb
- spec/unit/puppet/provider/chocolateysource/windows_spec.rb
- spec/unit/puppet/type/chocolateysource_spec.rb
Prior to this commit the `chocolateysource` type and provider did
not support the option to specify the `--allow-self-service` flag
when managing a source. This option causes Chocolatey to mark the
source as being usable with the C4B Self-Service feature as of
C4B v1.10.0. It requires Chocolatey 0.10.4+ to set this option.
This commit adds the `allow_self_service` property to the type and
provider of `chocolateysource` to ensure that this property
can be configured on versions which support it.
This commit also updates the README documentation and CHANGELOG,
as well as providing new unit and acceptance tests and updating
any unit and acceptance tests which should include the new
setting.
> (MODULES-5897) Add allow_self_service to chocolateysource

- lib/puppet/provider/chocolateyfeature/windows.rb
- spec/unit/puppet/provider/chocolateyfeature/windows_spec.rb
fix MODULES-6948 with changing the function name from features to choco_features. features is used by puppet internally to match providers and types (has_feature etc.). With renaming the feature function in the chocolateyfeature provider, it prevents this function to be executed when the types are getting generated on the master (and then fails because no chocolatey config can't be found).
> (MODULES-6948) Fix/generate types chocolateyfeature

- README.md
- manifests/init.pp
The existing documentation for the `chocolatey_version` parameter
of the `chocolatey` class is only in the init.pp file and briefly
mentioned in the documentation for the `chocolateyversion` fact.
None of these documentation sources cover that the parameter is
an optional informational flag to send to the class to help it
decide what behaviors to follow during execution.
A straight reading of the parameter name in the context of the
class is that it should pin Chocolatey to a particular version.
It does not and was not meant to do this. While a future ticket
may add this functionality it is important that we document and
clarify the current usage and make it easier for users to
understand.
This commit adds that documentation both to the class itself and
to the README.
> (MODULES-7042) Document chocolatey_version

- CHANGELOG.md
- README.md
- lib/puppet/provider/package/chocolatey.rb
- spec/unit/puppet/provider/package/chocolatey_spec.rb
When the "usepackageexitcodes" feature is enabled with the
chocolateyfeature resource, this commit ensures that the
--ignore-package-exit-codes argument is not passed to the choco binary
and that the feature is respected.
Previously, the --ignore-package-exit-codes argument would be passed all
the time (on versions of Chocolatey where it existed) and this would
result in the enabling of the "usepackageexitcodes" feature to be
rendered moot.
> (MODULES-5383) Remove exit codes arg with feature

- lib/puppet/provider/package/chocolatey.rb
Prior to this commit the package provider code did not
explicitly include REXML, which it relies on. This was
missed during unit tests which explicitly require the
appropriate library and was only discovered during
acceptance testing.
This commit ensures the appropriate requires is in
place.
> (MAINT) Fix broken state which causes CI to fail

- CHANGELOG.md
Add a changelog entry for the fix to allow installing Chocolatey
from behind a proxy, and to properly credit Geoff Williams for the code
contribution.
> (MAINT) Add a changelog entry

- lib/puppet/provider/chocolateyconfig/windows.rb
- lib/puppet/type/chocolateyconfig.rb
- spec/unit/puppet/provider/chocolateyconfig/windows_spec.rb
- spec/unit/puppet/type/chocolateyconfig_spec.rb
Prior to this commit running `puppet resource chocolateyconfig` would
fail during the validation block which verified that no config items
were both :present *and* had an empty :value or were missing :value
altogether.
This is because Chocolatey represents a configuration item which is
using the defaults as an empty string. When collecting instances of
Chocolatey config items from the configuration file, it would find
the items, mark them as :present, and save them with a :value of "".
This would then fail the validation block.
During a `puppet apply` run the validation block is called before the
instances are fetched - and, therefore, before `@property_hash` is
populated. This allows us to distinguish between the two calls and error
on any declared resources which specify `:ensure` as …
> (MODULES-8047) Fix puppet resource chocolateyconfig

- README.md
This commit adds a warning note to the package parameter documentation
on `install_options`, clarifying that it is _possible_ that secrets
will leak during a debug run and **guaranteed** that they will leak
to the Chocolatey log on the machine in any case.
The warning further advises users who need to use a secret in their
`install_options` to do the following:
1. Never run in debug mode with production credentials.
2. Acquire a C4B license and use the `--package-parameters-sensitive`
flag to redact the values from the Chocolatey log.
> (MODULES-8491) Warn about `install_options` secrets

- CHANGELOG.md
- README.md
- lib/facter/choco_temp_dir.rb
- lib/puppet_x/chocolatey/chocolatey_install.rb
- manifests/init.pp
- manifests/install.pp
- manifests/params.pp
- spec/classes/install_spec.rb
- spec/unit/facter/choco_temp_dir.rb
- spec/unit/puppet_x/chocolatey/chocolatey_install_spec.rb
- templates/InstallChocolatey.ps1.erb
Adds a local file '7za.exe' witch is copied to $::system32 in case unzip
method is '7zip'.
7za - source: https://chocolatey.org/7za.exe, witch was originally used
in the template.
> (MODULES-6652) Fix download 7z behind proxy

- metadata.json
As Puppet 4 is no longer supported, the supported bound is being raised.
No codes changes are included in this commit.
> (MODULES-9310) Raise lower Puppet bound to 5.5.10

- lib/puppet/provider/chocolateysource/windows.rb
- lib/puppet/type/chocolateysource.rb
- spec/acceptance/sources_spec.rb
- spec/unit/puppet/provider/chocolateysource/windows_spec.rb
This change redacts the commandline used with the `chocolateysource`
type if the user supplies a password.
If the user does not set a password for the source then no redaction
takes place. If a password is supplied then the entire commandline that
contains the password will be redacted.
This change also allows the user to specify a value to the `password`
parameter using the `Sensitive` data type, but note that this is not
required. The commandline will be redacted even if a normal string is
provided, and using the `Sensitive` type will cause Puppet to raise
a warning, even though nothing is wrong.
> (MODULES-9690) Redact Sensitive Commandline

- manifests/install.pp
Fixes $chocolatey_version to acually bootstrap the given version of
chocolatey.
> (MODULES-8521) Fix $chocolatey_version parameter

- metadata.json
Looks like puppetlabs-registry has been updated to v 3.0.0. puppetlabs-chocolatey currently depends on registry < 3.0.0
Change log looks pretty safe:
https://github.com/puppetlabs/puppetlabs-registry/compare/2.1.0...v3.0.0
> Update registry version_requirement

- lib/facter/chocolateyversion.rb
This commit updates chocolatey custom fact because the evaluation
of custom facts code has changed between Facter 2 and Facter 4.
In Facter 2, when a custom fact is loaded, the code in add block
was not executed.
In Facter 4, when a custom fact is loaded, the code outside setcode
block is executed (same as Facter 3).
> (maint) Move code for chocolatey version in setcode block

- lib/puppet_x/chocolatey/chocolatey_version.rb
Change originally encompassed install path as well but this was removed as it clashed with intended functionality.
> (MODULES-10704) - Have the code error out rather than return nil values when finding version

- metadata.json
This commit updates the dependency on `puppetlabs/stdlib` to allow
for 8.x versions.
> (MODULES-11206) Update dependencies to allow stdlib 8.x

- .fixtures.yml
- .github/workflows/spec.yml
- .sync.yml
- metadata.json
- spec/tasks/chocolatey_outdated_task_spec.rb
- spec/tasks/chocolatey_pin_task_spec.rb
- spec/tasks/chocolatey_status_task_spec.rb
- spec/tasks/chocolatey_task_spec.rb
- tasks/init.json
- tasks/init.rb
- tasks/outdated.json
- tasks/outdated.rb
- tasks/pin.json
- tasks/pin.rb
- tasks/status.json
- tasks/status.rb
Add a task to list current packages:
```
C:\> bolt task run chocolatey::status -t localhost
Started on localhost...
Finished on localhost:
{"status":[{"package":"chocolatey","version":"0.11.3"},{"package":"puppet-bolt","version":"3.20.0"}]}
Successful on 1 target: localhost
Ran on 1 target in 2.6 sec
C:\>
```
Add tasks to install, upgrade and uninstall packages:
```
C:\> bolt task run chocolatey action=install package=pdk version=2.0.0.0 -t localhost
C:\> bolt task run chocolatey action=upgrade package=pdk -t localhost
C:\> bolt task run chocolatey action=uninstall package=pdk -t localhost
```
Add a task to pin/unpin packages:
```
C:\> bolt task run chocolatey::pin action=add package=puppet-bolt -t localhost
C:\> bolt task run chocolatey::pin action=list -t localhost
Started on …
```
> (MODULES-11255) Add basic tasks to manage packages

- lib/puppet_x/chocolatey/chocolatey_common.rb
- spec/unit/puppet/provider/package/chocolatey_spec.rb
- spec/unit/puppet_x/chocolatey/chocolatey_common_spec.rb
Fixes #283 
In situations where the resource described in the manifest includes a version in its `ensure` property and `choco` v1 or above is installed, puppet runs would fail. This was happening of an issue where the version of chocolatey was not being properly derived by `choco_version`.
In turn, would cause `compiled_choco` to return false causing the module to default to using `choco update` rather than `choco upgrade`.
This PR fixes that by ensuring that the `choco_version` method returns the correct puppet version.
We can now observe the correct behaviour, even when the `chocolateyversion` fact has not been populated.
```bash
Debug: Facter: resolving fact with user_query: chocolateyversion
Debug: Facter: Searching fact: chocolateyversion in file: chocolateyversion.rb
Debug: Facter: …
```
> (GH-283) Fix deprecation error

- metadata.json
Prior to this commit the metadata.json file for this module listed OSs that are not supported by puppet agent as supported. This commit aims to refactor the metadata.json file to only list OSs that are supported by puppet agent.
In this commit:
- Support for Windows 7 and 8.1 was dropped.
- Support for Windows Server 2008 and 2008 R2 was dropped.
The list of supported OSs can be found here:
https://puppet.com/docs/pe/2021.7/supported_operating_systems.html
> (MAINT) Dropping of support for windows 7,8.1, 2008/2008R2 (Server)

- lib/puppet/provider/chocolateyconfig/windows.rb
- lib/puppet/provider/chocolateyfeature/windows.rb
- lib/puppet/provider/chocolateysource/windows.rb
- lib/puppet/provider/package/chocolatey.rb
- manifests/config.pp
- manifests/init.pp
- manifests/install.pp
- spec/unit/puppet/provider/chocolateyconfig/windows_spec.rb
- spec/unit/puppet/provider/chocolateysource/windows_spec.rb
As it stands certain sensitive parameters are being revealed within error and debug messages. This should prevent that.
Setting all to sensitive in order to be thorough, no reason not to.
> (CONT-708) Set all execute's to run with sensitive

- .github/workflows/ci.yml
- .github/workflows/nightly.yml
(MAINT) - Add env variables to ci
pdk version: `2.7.1` 
`Run Static & Syntax Tests` step moved from setup_matrix to spec job to be consistent with the other modules.
> pdksync - (MAINT) - Add env variables to ci

- spec/tasks/chocolatey_outdated_task_spec.rb
- spec/tasks/chocolatey_pin_task_spec.rb
- spec/tasks/chocolatey_status_task_spec.rb
- spec/tasks/chocolatey_task_spec.rb
- spec/unit/puppet/provider/package/chocolatey_spec.rb
Fixing rubocop smells
- N/A
- N/A
> (CAT-1274) - Fixing rubocop smells

- .rubocop_todo.yml
- spec/unit/facter/choco_temp_dir.rb
- spec/unit/puppet/provider/chocolateysource/windows_spec.rb
- spec/unit/puppet/provider/package/chocolatey_spec.rb
Fixing CI failure in rubocop
```
Add RSpec/MetadataStyle and RSpec/EmptyMetadata cops.
```
Mention any related issues or pull requests.
> [CAT-1382] : Fixing CI failure due to rubocop
